import type { User } from "./types";

export interface SeedUser extends User {
  interests: string[];
  voice_quote: string;
}

export const seedUsers: SeedUser[] = [
  {
    id: "u_franz",
    first_name: "Franz",
    email: "franz@eur.nl",
    age: 24,
    gender: "male",
    gender_preference: "mixed",
    neighbourhood: "Kralingen",
    languages_spoken: ["German", "English"],
    languages_comfortable: ["German", "English"],
    availability: ["thursday-evening", "every-weekend"],
    commitment_appetite: "maybe-weekly",
    verification_status: "verified",
    profile_completed: true,
    interests: ["catan", "board games", "strategy games", "german", "casual games"],
    voice_quote: "I keep coming back to Catan, honestly. Something about a slow Thursday game.",
  },
  {
    id: "u_lena",
    first_name: "Lena",
    email: "lena@eur.nl",
    age: 22,
    gender: "female",
    gender_preference: "mixed",
    neighbourhood: "Centrum",
    languages_spoken: ["German", "English"],
    languages_comfortable: ["English", "German"],
    availability: ["thursday-evening"],
    commitment_appetite: "maybe-weekly",
    verification_status: "verified",
    profile_completed: true,
    interests: ["catan", "board games", "coffee", "study cafés"],
    voice_quote: "Catan with some coffee on the side would actually be perfect.",
  },
  {
    id: "u_mark",
    first_name: "Mark",
    email: "mark@eur.nl",
    age: 26,
    gender: "male",
    gender_preference: "either",
    neighbourhood: "Kralingen",
    languages_spoken: ["English", "Dutch"],
    languages_comfortable: ["English"],
    availability: ["weekday-evenings"],
    commitment_appetite: "regular-thing",
    verification_status: "verified",
    profile_completed: true,
    interests: ["strategy games", "chess", "board games"],
    voice_quote: "Anything strategy — chess, board games. I miss the thinking-out-loud part.",
  },
  {
    id: "u_sara",
    first_name: "Sara",
    email: "sara@eur.nl",
    age: 23,
    gender: "female",
    gender_preference: "mixed",
    neighbourhood: "Kralingen",
    languages_spoken: ["English", "Spanish"],
    languages_comfortable: ["English", "Spanish"],
    availability: ["thursday-evening", "friday-morning"],
    commitment_appetite: "try-once",
    verification_status: "verified",
    profile_completed: true,
    interests: ["casual games", "language exchange", "food spots"],
    voice_quote: "I'd be up for a casual game night — nothing too intense though.",
  },
  {
    id: "u_noor",
    first_name: "Noor",
    email: "noor@eur.nl",
    age: 25,
    gender: "female",
    gender_preference: "mixed",
    neighbourhood: "Noord",
    languages_spoken: ["Dutch", "English"],
    languages_comfortable: ["Dutch", "English"],
    availability: ["every-weekend"],
    commitment_appetite: "maybe-weekly",
    verification_status: "verified",
    profile_completed: true,
    interests: ["running", "photography", "weekend walks"],
    voice_quote: "Weekend runs and taking photos along the way — that's my thing right now.",
  },
  {
    id: "u_jonas",
    first_name: "Jonas",
    email: "jonas@eur.nl",
    age: 21,
    gender: "male",
    gender_preference: "mixed",
    neighbourhood: "Delfshaven",
    languages_spoken: ["English", "Dutch"],
    languages_comfortable: ["English"],
    availability: ["friday-morning"],
    commitment_appetite: "try-once",
    verification_status: "verified",
    profile_completed: true,
    interests: ["music production", "techno", "ableton"],
    voice_quote: "I make techno alone too much. Would love to bounce ideas with someone.",
  },
  {
    id: "u_emma",
    first_name: "Emma",
    email: "emma@eur.nl",
    age: 27,
    gender: "female",
    gender_preference: "same-gender",
    neighbourhood: "Centrum",
    languages_spoken: ["English"],
    languages_comfortable: ["English"],
    availability: ["every-weekend"],
    commitment_appetite: "maybe-weekly",
    verification_status: "verified",
    profile_completed: true,
    interests: ["ceramics", "creative workshops", "tea"],
    voice_quote: "Anything where my hands are busy and there's tea — ceramics, workshops.",
  },
  {
    id: "u_amir",
    first_name: "Amir",
    email: "amir@eur.nl",
    age: 23,
    gender: "male",
    gender_preference: "mixed",
    neighbourhood: "Centrum",
    languages_spoken: ["English", "Arabic"],
    languages_comfortable: ["English"],
    availability: ["weekday-evenings"],
    commitment_appetite: "regular-thing",
    verification_status: "verified",
    profile_completed: true,
    interests: ["football", "gym", "food", "casual hangouts"],
    voice_quote: "Football, gym, maybe grabbing food after. Active stuff mostly.",
  },
  {
    id: "u_sophie",
    first_name: "Sophie",
    email: "sophie@eur.nl",
    age: 22,
    gender: "female",
    gender_preference: "mixed",
    neighbourhood: "Kralingen",
    languages_spoken: ["English", "French"],
    languages_comfortable: ["English"],
    availability: ["thursday-evening"],
    commitment_appetite: "maybe-weekly",
    verification_status: "verified",
    profile_completed: true,
    interests: ["catan", "ticket to ride", "board games"],
    voice_quote: "Catan, Ticket to Ride — board game nights are kind of my comfort zone.",
  },
  {
    id: "u_david",
    first_name: "David",
    email: "david@eur.nl",
    age: 25,
    gender: "male",
    gender_preference: "mixed",
    neighbourhood: "Noord",
    languages_spoken: ["English", "Dutch"],
    languages_comfortable: ["English", "Dutch"],
    availability: ["thursday-evening"],
    commitment_appetite: "maybe-weekly",
    verification_status: "verified",
    profile_completed: true,
    interests: ["running", "outdoors"],
    voice_quote: "Honestly board games aren't for me. Running and being outside, that's it.",
  },
  {
    id: "u_clara",
    first_name: "Clara",
    email: "clara@eur.nl",
    age: 24,
    gender: "female",
    gender_preference: "mixed",
    neighbourhood: "Centrum",
    languages_spoken: ["German", "English"],
    languages_comfortable: ["German", "English"],
    availability: ["friday-morning"],
    commitment_appetite: "maybe-weekly",
    verification_status: "verified",
    profile_completed: true,
    interests: ["language exchange", "cafés", "German-English"],
    voice_quote: "I'd love a relaxed German-English language café on Friday mornings.",
  },
  {
    id: "u_milan",
    first_name: "Milan",
    email: "milan@eur.nl",
    age: 26,
    gender: "male",
    gender_preference: "mixed",
    neighbourhood: "Kralingen",
    languages_spoken: ["English", "Dutch"],
    languages_comfortable: ["English"],
    availability: ["every-weekend"],
    commitment_appetite: "try-once",
    verification_status: "verified",
    profile_completed: true,
    interests: ["film photography", "rotterdam walks", "architecture"],
    voice_quote: "Film photography, Rotterdam side streets, that kind of slow Saturday.",
  },
];

export const findUser = (id: string): SeedUser | undefined =>
  seedUsers.find((u) => u.id === id);

export const sampleVoiceTranscript = `So, lately I've been getting back into board games. Mostly Catan honestly — I used to play a lot with my brother and I keep thinking about it. I'd love to do a proper round again, nothing too competitive, just a chill Thursday evening kind of thing.
I also like strategy games in general, like Ticket to Ride, even a casual chess match every now and then. I'm comfortable in English mostly but I also speak German if anyone else does. I'm in Kralingen so anything near campus would be ideal.
I think a small group of four would be perfect — I'm not into big game nights with twelve people. Just one game, one drink, see how it feels. Maybe make it a regular thing if it clicks, but no pressure.
Thursday evenings work best for me. I'm not really available on weekends because I usually visit family. I'm honestly just looking to start something low-pressure, see if it sticks.`;

export const sampleMainTopics = [
  {
    id: "t_catan",
    title: "Settlers of Catan",
    explanation:
      "You talked about wanting to play Catan again in a low-pressure setting.",
    tags: ["catan", "board games", "specific game"],
  },
  {
    id: "t_boardgames",
    title: "Board games",
    explanation: "Strategy games and casual game nights came up strongly.",
    tags: ["board games", "strategy games", "casual games"],
  },
  {
    id: "t_thursday",
    title: "Thursday evenings",
    explanation: "This seems like a realistic time for you.",
    tags: ["thursday-evening"],
  },
  {
    id: "t_languages",
    title: "English and German",
    explanation: "You seem comfortable with both.",
    tags: ["english", "german"],
  },
  {
    id: "t_smallgroup",
    title: "Small groups",
    explanation: "You mentioned preferring something calm over a big event.",
    tags: ["small group", "low-pressure"],
  },
];

export const sampleMinorInterests = [
  "Coffee on the side",
  "Near campus",
  "Ticket to Ride",
  "One drink, one game",
  "Open to making it weekly",
];

export const sampleActivityTypes = [
  "Sit-down",
  "Games",
  "Low-pressure first meeting",
  "Activity-led conversation",
];
